version: "3.8"

services:
    astra_agents_server:
        image: agoraio/astra_agents_server:latest
        container_name: astra_agents_server
        restart: always
        ports:
            - "${SERVER_PORT}:${SERVER_PORT}"
        volumes:
            - ${LOG_PATH}:${LOG_PATH}
        environment:
            AGORA_APP_ID: ${AGORA_APP_ID}
            AGORA_APP_CERTIFICATE: ${AGORA_APP_CERTIFICATE}
            AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
            AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
            AWS_BEDROCK_MODEL: ${AWS_BEDROCK_MODEL}
            AWS_REGION: ${AWS_REGION}
            AZURE_STT_KEY: ${AZURE_STT_KEY}
            AZURE_STT_REGION: ${AZURE_STT_REGION}
            AZURE_TTS_KEY: ${AZURE_TTS_KEY}
            AZURE_TTS_REGION: ${AZURE_TTS_REGION}
            COSY_TTS_KEY: ${COSY_TTS_KEY}
            ELEVENLABS_TTS_KEY: ${ELEVENLABS_TTS_KEY}
            OPENAI_API_KEY: ${OPENAI_API_KEY}
            OPENAI_BASE_URL: ${OPENAI_BASE_URL}
            OPENAI_MODEL: ${OPENAI_MODEL}
            PROXY_URL: ${PROXY_URL}
            QWEN_API_KEY: ${QWEN_API_KEY}
        build:
            context: .
            dockerfile: Dockerfile
        platform: linux/amd64
    astra_playground:
        image: agoraio/astra_playground:latest
        container_name: astra_playground
        restart: always
        ports:
            - "3000:3000"
        build:
            context: ./playground
            dockerfile: Dockerfile
