version: '3.8'
services:
  astra_agents_dev:
    image: ${ASTRA_AGENTS_IMAGE:-ghcr.io/ten-framework/astra_agents_build:0.4.0}
    container_name: astra_agents_dev
    platform: linux/amd64
    tty: true
    stdin_open: true
    restart: always
    command: sh -c "make debug-build-agents && make run-server"
    ports:
      - '${GRAPH_DESIGNER_SERVER_PORT}:${GRAPH_DESIGNER_SERVER_PORT}'
      - '${SERVER_PORT}:${SERVER_PORT}'
    volumes:
      - ./:/app
      - ${LOG_PATH}:${LOG_PATH}
    working_dir: /app
    env_file:
      - .env
    environment:
      - OS=${OS:-linux}
      - CPU=${CPU:-x64}
    build:
      context: .
      dockerfile: Dockerfile

  astra_playground:
    image: ${ASTRA_PLAYGROUND_IMAGE:-ghcr.io/ten-framework/astra_playground:v0.4.0-26-g9a72676}
    container_name: astra_playground
    restart: always
    ports:
      - '3000:3000'
    build:
      context: ./playground
      dockerfile: Dockerfile

  # use this when you want to run the playground in local development mode
  # astra_playground_dev:
  #     image: node:20-alpine
  #     container_name: astra_playground_dev
  #     restart: always
  #     command: sh -c "cd /app/playground && npm i && npm run dev" #build && npm run start"
  #     ports:
  #     - "3002:3000"
  #     volumes:
  #     - ./:/app
  ten_graph_designer:
    image: ghcr.io/ten-framework/ten_graph_designer:72db9b2
    container_name: ten_graph_designer
    restart: always
    ports:
      - '3001:3000'
