name: Build Docker

on: 
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
    paths-ignore:
      - '.devcontainer/**'
      - '.github/ISSUE_TEMPLATE/**'
      - 'images/**'
      - 'frontend/**'
      - '**.md'
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  SERVER_IMAGE_NAME: ten_agent_server
  FRONTEND_IMAGE_NAME: ten_agent_frontend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-tags: true
        fetch-depth: '0'
    - id: pre-step
      shell: bash
      run: echo "image-tag=$(git describe --tags --always)" >> $GITHUB_OUTPUT
    - name: Build & Publish Docker Image for Agents Server 
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: ${{ github.repository_owner }}/${{ env.SERVER_IMAGE_NAME }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
        tags: "${{ github.ref == 'refs/heads/main' && 'latest,' || '' }}${{ steps.pre-step.outputs.image-tag }}"
        no_push: ${{ github.event_name == 'pull_request' }}
    - name: Build & Publish Docker Image for Frontend
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: ${{ github.repository_owner }}/${{ env.FRONTEND_IMAGE_NAME }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
        workdir: frontend
        tags: "${{ github.ref == 'refs/heads/main' && 'latest,' || '' }}${{ steps.pre-step.outputs.image-tag }}"
        no_push: ${{ github.event_name == 'pull_request' }}
